/* tslint:disable */
/* eslint-disable */
/**
 * TP.Profile.Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AssistantListingReq
 */
export interface AssistantListingReq {
    /**
     * 
     * @type {number}
     * @memberof AssistantListingReq
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof AssistantListingReq
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof AssistantListingReq
     */
    search?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AssistantListingReq
     */
    sort?: string | null;
}
