/* tslint:disable */
/* eslint-disable */
/**
 * TP.Profile.Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AssistantListItem } from './assistant-list-item';
/**
 * 
 * @export
 * @interface AssistantListingRes
 */
export interface AssistantListingRes {
    /**
     * 
     * @type {Array<AssistantListItem>}
     * @memberof AssistantListingRes
     */
    assistants?: Array<AssistantListItem> | null;
    /**
     * 
     * @type {number}
     * @memberof AssistantListingRes
     */
    total: number;
}
