/* tslint:disable */
/* eslint-disable */
/**
 * TP.Profile.Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GenderType } from './gender-type';
import { ProfileType } from './profile-type';
/**
 * 
 * @export
 * @interface AssistantListItem
 */
export interface AssistantListItem {
    /**
     * 
     * @type {string}
     * @memberof AssistantListItem
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AssistantListItem
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof AssistantListItem
     */
    lastname: string;
    /**
     * 
     * @type {string}
     * @memberof AssistantListItem
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof AssistantListItem
     */
    phone?: string | null;
    /**
     * 
     * @type {ProfileType}
     * @memberof AssistantListItem
     */
    type?: ProfileType;
    /**
     * 
     * @type {number}
     * @memberof AssistantListItem
     */
    createdAt?: number;
    /**
     * 
     * @type {number}
     * @memberof AssistantListItem
     */
    birthDate?: number | null;
    /**
     * 
     * @type {string}
     * @memberof AssistantListItem
     */
    bio?: string | null;
    /**
     * 
     * @type {GenderType}
     * @memberof AssistantListItem
     */
    gender?: GenderType;
    /**
     * 
     * @type {Array<string>}
     * @memberof AssistantListItem
     */
    interests?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof AssistantListItem
     */
    image?: string | null;
}
