/* tslint:disable */
/* eslint-disable */
/**
 * TP.Profile.Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface InterestDto
 */
export interface InterestDto {
    /**
     * 
     * @type {string}
     * @memberof InterestDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof InterestDto
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof InterestDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof InterestDto
     */
    createdAt?: number;
    /**
     * 
     * @type {number}
     * @memberof InterestDto
     */
    order?: number;
}
