/* tslint:disable */
/* eslint-disable */
/**
 * TP.Profile.Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ProfileSettingDto
 */
export interface ProfileSettingDto {
    /**
     * 
     * @type {boolean}
     * @memberof ProfileSettingDto
     */
    available?: boolean;
    /**
     * 
     * @type {number}
     * @memberof ProfileSettingDto
     */
    timeIncludeFrom?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProfileSettingDto
     */
    timeIncludeTo?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProfileSettingDto
     */
    dateExcludeFrom?: number | null;
    /**
     * 
     * @type {number}
     * @memberof ProfileSettingDto
     */
    dateExcludeTo?: number | null;
}
