/* tslint:disable */
/* eslint-disable */
/**
 * TP.Profile.Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GenderType } from './gender-type';
/**
 * 
 * @export
 * @interface UserRegisterReq
 */
export interface UserRegisterReq {
    /**
     * 
     * @type {string}
     * @memberof UserRegisterReq
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterReq
     */
    lastname: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterReq
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterReq
     */
    password: string;
    /**
     * 
     * @type {GenderType}
     * @memberof UserRegisterReq
     */
    gender: GenderType;
}
