/* tslint:disable */
/* eslint-disable */
/**
 * TP.Profile.Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { EmailPasswordLoginReq } from '../models';
import { LoginRes } from '../models';
import { RefreshTokenReq } from '../models';
/**
 * AdminAuthApi - axios parameter creator
 * @export
 */
export const AdminAuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {EmailPasswordLoginReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminAuthLoginPost: async (body?: EmailPasswordLoginReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/AdminAuth/Login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RefreshTokenReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adminAuthRefreshTokenPost: async (body?: RefreshTokenReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/AdminAuth/RefreshToken`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AdminAuthApi - functional programming interface
 * @export
 */
export const AdminAuthApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {EmailPasswordLoginReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminAuthLoginPost(body?: EmailPasswordLoginReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LoginRes>>> {
            const localVarAxiosArgs = await AdminAuthApiAxiosParamCreator(configuration).adminAuthLoginPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {RefreshTokenReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminAuthRefreshTokenPost(body?: RefreshTokenReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LoginRes>>> {
            const localVarAxiosArgs = await AdminAuthApiAxiosParamCreator(configuration).adminAuthRefreshTokenPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AdminAuthApi - factory interface
 * @export
 */
export const AdminAuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {EmailPasswordLoginReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminAuthLoginPost(body?: EmailPasswordLoginReq, options?: AxiosRequestConfig): Promise<AxiosResponse<LoginRes>> {
            return AdminAuthApiFp(configuration).adminAuthLoginPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RefreshTokenReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adminAuthRefreshTokenPost(body?: RefreshTokenReq, options?: AxiosRequestConfig): Promise<AxiosResponse<LoginRes>> {
            return AdminAuthApiFp(configuration).adminAuthRefreshTokenPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AdminAuthApi - object-oriented interface
 * @export
 * @class AdminAuthApi
 * @extends {BaseAPI}
 */
export class AdminAuthApi extends BaseAPI {
    /**
     * 
     * @param {EmailPasswordLoginReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuthApi
     */
    public async adminAuthLoginPost(body?: EmailPasswordLoginReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<LoginRes>> {
        return AdminAuthApiFp(this.configuration).adminAuthLoginPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {RefreshTokenReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminAuthApi
     */
    public async adminAuthRefreshTokenPost(body?: RefreshTokenReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<LoginRes>> {
        return AdminAuthApiFp(this.configuration).adminAuthRefreshTokenPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
