/* tslint:disable */
/* eslint-disable */
/**
 * TP.Profile.Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AssistantListingReq } from '../models';
import { AssistantListingRes } from '../models';
/**
 * AssistantListingApi - axios parameter creator
 * @export
 */
export const AssistantListingApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AssistantListingReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assistantListingListingPost: async (body?: AssistantListingReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/AssistantListing/Listing`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {AssistantListingReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assistantListingUserListingPost: async (body?: AssistantListingReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/AssistantListing/UserListing`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AssistantListingApi - functional programming interface
 * @export
 */
export const AssistantListingApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {AssistantListingReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assistantListingListingPost(body?: AssistantListingReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AssistantListingRes>>> {
            const localVarAxiosArgs = await AssistantListingApiAxiosParamCreator(configuration).assistantListingListingPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {AssistantListingReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assistantListingUserListingPost(body?: AssistantListingReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<AssistantListingRes>>> {
            const localVarAxiosArgs = await AssistantListingApiAxiosParamCreator(configuration).assistantListingUserListingPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * AssistantListingApi - factory interface
 * @export
 */
export const AssistantListingApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {AssistantListingReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assistantListingListingPost(body?: AssistantListingReq, options?: AxiosRequestConfig): Promise<AxiosResponse<AssistantListingRes>> {
            return AssistantListingApiFp(configuration).assistantListingListingPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AssistantListingReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assistantListingUserListingPost(body?: AssistantListingReq, options?: AxiosRequestConfig): Promise<AxiosResponse<AssistantListingRes>> {
            return AssistantListingApiFp(configuration).assistantListingUserListingPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AssistantListingApi - object-oriented interface
 * @export
 * @class AssistantListingApi
 * @extends {BaseAPI}
 */
export class AssistantListingApi extends BaseAPI {
    /**
     * 
     * @param {AssistantListingReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssistantListingApi
     */
    public async assistantListingListingPost(body?: AssistantListingReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<AssistantListingRes>> {
        return AssistantListingApiFp(this.configuration).assistantListingListingPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {AssistantListingReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssistantListingApi
     */
    public async assistantListingUserListingPost(body?: AssistantListingReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<AssistantListingRes>> {
        return AssistantListingApiFp(this.configuration).assistantListingUserListingPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
