/* tslint:disable */
/* eslint-disable */
/**
 * TP.Profile.Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { AddInterestReq } from '../models';
import { EmptyResponse } from '../models';
import { InterestDto } from '../models';
import { InterestUpdateReq } from '../models';
/**
 * InterestApi - axios parameter creator
 * @export
 */
export const InterestApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        interestForceUpdateCachePost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Interest/ForceUpdateCache`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        interestGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Interest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {InterestUpdateReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        interestPatch: async (body?: InterestUpdateReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Interest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {AddInterestReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        interestPost: async (body?: AddInterestReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/Interest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InterestApi - functional programming interface
 * @export
 */
export const InterestApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async interestForceUpdateCachePost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EmptyResponse>>> {
            const localVarAxiosArgs = await InterestApiAxiosParamCreator(configuration).interestForceUpdateCachePost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async interestGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<InterestDto>>>> {
            const localVarAxiosArgs = await InterestApiAxiosParamCreator(configuration).interestGet(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {InterestUpdateReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async interestPatch(body?: InterestUpdateReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EmptyResponse>>> {
            const localVarAxiosArgs = await InterestApiAxiosParamCreator(configuration).interestPatch(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {AddInterestReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async interestPost(body?: AddInterestReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<InterestDto>>> {
            const localVarAxiosArgs = await InterestApiAxiosParamCreator(configuration).interestPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * InterestApi - factory interface
 * @export
 */
export const InterestApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async interestForceUpdateCachePost(options?: AxiosRequestConfig): Promise<AxiosResponse<EmptyResponse>> {
            return InterestApiFp(configuration).interestForceUpdateCachePost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async interestGet(options?: AxiosRequestConfig): Promise<AxiosResponse<Array<InterestDto>>> {
            return InterestApiFp(configuration).interestGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {InterestUpdateReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async interestPatch(body?: InterestUpdateReq, options?: AxiosRequestConfig): Promise<AxiosResponse<EmptyResponse>> {
            return InterestApiFp(configuration).interestPatch(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AddInterestReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async interestPost(body?: AddInterestReq, options?: AxiosRequestConfig): Promise<AxiosResponse<InterestDto>> {
            return InterestApiFp(configuration).interestPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InterestApi - object-oriented interface
 * @export
 * @class InterestApi
 * @extends {BaseAPI}
 */
export class InterestApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InterestApi
     */
    public async interestForceUpdateCachePost(options?: AxiosRequestConfig) : Promise<AxiosResponse<EmptyResponse>> {
        return InterestApiFp(this.configuration).interestForceUpdateCachePost(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InterestApi
     */
    public async interestGet(options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<InterestDto>>> {
        return InterestApiFp(this.configuration).interestGet(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {InterestUpdateReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InterestApi
     */
    public async interestPatch(body?: InterestUpdateReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<EmptyResponse>> {
        return InterestApiFp(this.configuration).interestPatch(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {AddInterestReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof InterestApi
     */
    public async interestPost(body?: AddInterestReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<InterestDto>> {
        return InterestApiFp(this.configuration).interestPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
