/* tslint:disable */
/* eslint-disable */
/**
 * TP.Profile.Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { EmptyResponse } from '../models';
import { OtpForgetPasswordRes } from '../models';
import { SendEmailVerifyRes } from '../models';
import { UpdatePasswordReq } from '../models';
import { ValidateEmailReq } from '../models';
import { ValidateOtpUpdatePasswordReq } from '../models';
import { ValidatePhoneVerificationReq } from '../models';
import { VerifyPhoneReq } from '../models';
import { VerifyPhoneRes } from '../models';
/**
 * ProfileSecurityApi - axios parameter creator
 * @export
 */
export const ProfileSecurityApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ValidateEmailReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileSecurityEmailVerifyPatch: async (body?: ValidateEmailReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ProfileSecurity/EmailVerify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileSecuritySendEmailVerifyRequestPost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ProfileSecurity/SendEmailVerifyRequest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileSecurityUpdatePasswordOtpRequestPost: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ProfileSecurity/UpdatePasswordOtpRequest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ValidateOtpUpdatePasswordReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileSecurityUpdatePasswordOtpVerifyPatch: async (body?: ValidateOtpUpdatePasswordReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ProfileSecurity/UpdatePasswordOtpVerify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdatePasswordReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileSecurityUpdatePasswordPatch: async (body?: UpdatePasswordReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ProfileSecurity/UpdatePassword`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {VerifyPhoneReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileSecurityUpdatePhoneRequestPost: async (body?: VerifyPhoneReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ProfileSecurity/UpdatePhoneRequest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {ValidatePhoneVerificationReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        profileSecurityUpdatePhoneVerifyPatch: async (body?: ValidatePhoneVerificationReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ProfileSecurity/UpdatePhoneVerify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProfileSecurityApi - functional programming interface
 * @export
 */
export const ProfileSecurityApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {ValidateEmailReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileSecurityEmailVerifyPatch(body?: ValidateEmailReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EmptyResponse>>> {
            const localVarAxiosArgs = await ProfileSecurityApiAxiosParamCreator(configuration).profileSecurityEmailVerifyPatch(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileSecuritySendEmailVerifyRequestPost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<SendEmailVerifyRes>>> {
            const localVarAxiosArgs = await ProfileSecurityApiAxiosParamCreator(configuration).profileSecuritySendEmailVerifyRequestPost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileSecurityUpdatePasswordOtpRequestPost(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<OtpForgetPasswordRes>>> {
            const localVarAxiosArgs = await ProfileSecurityApiAxiosParamCreator(configuration).profileSecurityUpdatePasswordOtpRequestPost(options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {ValidateOtpUpdatePasswordReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileSecurityUpdatePasswordOtpVerifyPatch(body?: ValidateOtpUpdatePasswordReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EmptyResponse>>> {
            const localVarAxiosArgs = await ProfileSecurityApiAxiosParamCreator(configuration).profileSecurityUpdatePasswordOtpVerifyPatch(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {UpdatePasswordReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileSecurityUpdatePasswordPatch(body?: UpdatePasswordReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EmptyResponse>>> {
            const localVarAxiosArgs = await ProfileSecurityApiAxiosParamCreator(configuration).profileSecurityUpdatePasswordPatch(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {VerifyPhoneReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileSecurityUpdatePhoneRequestPost(body?: VerifyPhoneReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<VerifyPhoneRes>>> {
            const localVarAxiosArgs = await ProfileSecurityApiAxiosParamCreator(configuration).profileSecurityUpdatePhoneRequestPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {ValidatePhoneVerificationReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileSecurityUpdatePhoneVerifyPatch(body?: ValidatePhoneVerificationReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<EmptyResponse>>> {
            const localVarAxiosArgs = await ProfileSecurityApiAxiosParamCreator(configuration).profileSecurityUpdatePhoneVerifyPatch(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ProfileSecurityApi - factory interface
 * @export
 */
export const ProfileSecurityApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {ValidateEmailReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileSecurityEmailVerifyPatch(body?: ValidateEmailReq, options?: AxiosRequestConfig): Promise<AxiosResponse<EmptyResponse>> {
            return ProfileSecurityApiFp(configuration).profileSecurityEmailVerifyPatch(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileSecuritySendEmailVerifyRequestPost(options?: AxiosRequestConfig): Promise<AxiosResponse<SendEmailVerifyRes>> {
            return ProfileSecurityApiFp(configuration).profileSecuritySendEmailVerifyRequestPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileSecurityUpdatePasswordOtpRequestPost(options?: AxiosRequestConfig): Promise<AxiosResponse<OtpForgetPasswordRes>> {
            return ProfileSecurityApiFp(configuration).profileSecurityUpdatePasswordOtpRequestPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ValidateOtpUpdatePasswordReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileSecurityUpdatePasswordOtpVerifyPatch(body?: ValidateOtpUpdatePasswordReq, options?: AxiosRequestConfig): Promise<AxiosResponse<EmptyResponse>> {
            return ProfileSecurityApiFp(configuration).profileSecurityUpdatePasswordOtpVerifyPatch(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdatePasswordReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileSecurityUpdatePasswordPatch(body?: UpdatePasswordReq, options?: AxiosRequestConfig): Promise<AxiosResponse<EmptyResponse>> {
            return ProfileSecurityApiFp(configuration).profileSecurityUpdatePasswordPatch(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {VerifyPhoneReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileSecurityUpdatePhoneRequestPost(body?: VerifyPhoneReq, options?: AxiosRequestConfig): Promise<AxiosResponse<VerifyPhoneRes>> {
            return ProfileSecurityApiFp(configuration).profileSecurityUpdatePhoneRequestPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {ValidatePhoneVerificationReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async profileSecurityUpdatePhoneVerifyPatch(body?: ValidatePhoneVerificationReq, options?: AxiosRequestConfig): Promise<AxiosResponse<EmptyResponse>> {
            return ProfileSecurityApiFp(configuration).profileSecurityUpdatePhoneVerifyPatch(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProfileSecurityApi - object-oriented interface
 * @export
 * @class ProfileSecurityApi
 * @extends {BaseAPI}
 */
export class ProfileSecurityApi extends BaseAPI {
    /**
     * 
     * @param {ValidateEmailReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileSecurityApi
     */
    public async profileSecurityEmailVerifyPatch(body?: ValidateEmailReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<EmptyResponse>> {
        return ProfileSecurityApiFp(this.configuration).profileSecurityEmailVerifyPatch(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileSecurityApi
     */
    public async profileSecuritySendEmailVerifyRequestPost(options?: AxiosRequestConfig) : Promise<AxiosResponse<SendEmailVerifyRes>> {
        return ProfileSecurityApiFp(this.configuration).profileSecuritySendEmailVerifyRequestPost(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileSecurityApi
     */
    public async profileSecurityUpdatePasswordOtpRequestPost(options?: AxiosRequestConfig) : Promise<AxiosResponse<OtpForgetPasswordRes>> {
        return ProfileSecurityApiFp(this.configuration).profileSecurityUpdatePasswordOtpRequestPost(options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {ValidateOtpUpdatePasswordReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileSecurityApi
     */
    public async profileSecurityUpdatePasswordOtpVerifyPatch(body?: ValidateOtpUpdatePasswordReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<EmptyResponse>> {
        return ProfileSecurityApiFp(this.configuration).profileSecurityUpdatePasswordOtpVerifyPatch(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {UpdatePasswordReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileSecurityApi
     */
    public async profileSecurityUpdatePasswordPatch(body?: UpdatePasswordReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<EmptyResponse>> {
        return ProfileSecurityApiFp(this.configuration).profileSecurityUpdatePasswordPatch(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {VerifyPhoneReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileSecurityApi
     */
    public async profileSecurityUpdatePhoneRequestPost(body?: VerifyPhoneReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<VerifyPhoneRes>> {
        return ProfileSecurityApiFp(this.configuration).profileSecurityUpdatePhoneRequestPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {ValidatePhoneVerificationReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProfileSecurityApi
     */
    public async profileSecurityUpdatePhoneVerifyPatch(body?: ValidatePhoneVerificationReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<EmptyResponse>> {
        return ProfileSecurityApiFp(this.configuration).profileSecurityUpdatePhoneVerifyPatch(body, options).then((request) => request(this.axios, this.basePath));
    }
}
