/* tslint:disable */
/* eslint-disable */
/**
 * TP.Profile.Service
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { EmailPasswordLoginReq } from '../models';
import { LoginRes } from '../models';
import { OtpLoginReq } from '../models';
import { OtpLoginValidateReq } from '../models';
import { OtpRequestRes } from '../models';
import { RefreshTokenReq } from '../models';
import { UserRegisterReq } from '../models';
/**
 * UserAuthApi - axios parameter creator
 * @export
 */
export const UserAuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {RefreshTokenReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAuthGoogleLoginPost: async (body?: RefreshTokenReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/UserAuth/GoogleLogin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {EmailPasswordLoginReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAuthLoginPost: async (body?: EmailPasswordLoginReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/UserAuth/Login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {OtpLoginReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAuthOtpLoginRequestPost: async (body?: OtpLoginReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/UserAuth/OtpLoginRequest`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {OtpLoginValidateReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAuthOtpLoginValidatePost: async (body?: OtpLoginValidateReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/UserAuth/OtpLoginValidate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RefreshTokenReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAuthRefreshTokenPost: async (body?: RefreshTokenReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/UserAuth/RefreshToken`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UserRegisterReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        userAuthRegisterPost: async (body?: UserRegisterReq, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/UserAuth/Register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Bearer required

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserAuthApi - functional programming interface
 * @export
 */
export const UserAuthApiFp = function(configuration?: Configuration) {
    return {
        /**
         * 
         * @param {RefreshTokenReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAuthGoogleLoginPost(body?: RefreshTokenReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LoginRes>>> {
            const localVarAxiosArgs = await UserAuthApiAxiosParamCreator(configuration).userAuthGoogleLoginPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {EmailPasswordLoginReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAuthLoginPost(body?: EmailPasswordLoginReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LoginRes>>> {
            const localVarAxiosArgs = await UserAuthApiAxiosParamCreator(configuration).userAuthLoginPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {OtpLoginReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAuthOtpLoginRequestPost(body?: OtpLoginReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<OtpRequestRes>>> {
            const localVarAxiosArgs = await UserAuthApiAxiosParamCreator(configuration).userAuthOtpLoginRequestPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {OtpLoginValidateReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAuthOtpLoginValidatePost(body?: OtpLoginValidateReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LoginRes>>> {
            const localVarAxiosArgs = await UserAuthApiAxiosParamCreator(configuration).userAuthOtpLoginValidatePost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {RefreshTokenReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAuthRefreshTokenPost(body?: RefreshTokenReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LoginRes>>> {
            const localVarAxiosArgs = await UserAuthApiAxiosParamCreator(configuration).userAuthRefreshTokenPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {UserRegisterReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAuthRegisterPost(body?: UserRegisterReq, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<LoginRes>>> {
            const localVarAxiosArgs = await UserAuthApiAxiosParamCreator(configuration).userAuthRegisterPost(body, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * UserAuthApi - factory interface
 * @export
 */
export const UserAuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * 
         * @param {RefreshTokenReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAuthGoogleLoginPost(body?: RefreshTokenReq, options?: AxiosRequestConfig): Promise<AxiosResponse<LoginRes>> {
            return UserAuthApiFp(configuration).userAuthGoogleLoginPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {EmailPasswordLoginReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAuthLoginPost(body?: EmailPasswordLoginReq, options?: AxiosRequestConfig): Promise<AxiosResponse<LoginRes>> {
            return UserAuthApiFp(configuration).userAuthLoginPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OtpLoginReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAuthOtpLoginRequestPost(body?: OtpLoginReq, options?: AxiosRequestConfig): Promise<AxiosResponse<OtpRequestRes>> {
            return UserAuthApiFp(configuration).userAuthOtpLoginRequestPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {OtpLoginValidateReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAuthOtpLoginValidatePost(body?: OtpLoginValidateReq, options?: AxiosRequestConfig): Promise<AxiosResponse<LoginRes>> {
            return UserAuthApiFp(configuration).userAuthOtpLoginValidatePost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RefreshTokenReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAuthRefreshTokenPost(body?: RefreshTokenReq, options?: AxiosRequestConfig): Promise<AxiosResponse<LoginRes>> {
            return UserAuthApiFp(configuration).userAuthRefreshTokenPost(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UserRegisterReq} [body] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async userAuthRegisterPost(body?: UserRegisterReq, options?: AxiosRequestConfig): Promise<AxiosResponse<LoginRes>> {
            return UserAuthApiFp(configuration).userAuthRegisterPost(body, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserAuthApi - object-oriented interface
 * @export
 * @class UserAuthApi
 * @extends {BaseAPI}
 */
export class UserAuthApi extends BaseAPI {
    /**
     * 
     * @param {RefreshTokenReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAuthApi
     */
    public async userAuthGoogleLoginPost(body?: RefreshTokenReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<LoginRes>> {
        return UserAuthApiFp(this.configuration).userAuthGoogleLoginPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {EmailPasswordLoginReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAuthApi
     */
    public async userAuthLoginPost(body?: EmailPasswordLoginReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<LoginRes>> {
        return UserAuthApiFp(this.configuration).userAuthLoginPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {OtpLoginReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAuthApi
     */
    public async userAuthOtpLoginRequestPost(body?: OtpLoginReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<OtpRequestRes>> {
        return UserAuthApiFp(this.configuration).userAuthOtpLoginRequestPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {OtpLoginValidateReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAuthApi
     */
    public async userAuthOtpLoginValidatePost(body?: OtpLoginValidateReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<LoginRes>> {
        return UserAuthApiFp(this.configuration).userAuthOtpLoginValidatePost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {RefreshTokenReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAuthApi
     */
    public async userAuthRefreshTokenPost(body?: RefreshTokenReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<LoginRes>> {
        return UserAuthApiFp(this.configuration).userAuthRefreshTokenPost(body, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {UserRegisterReq} [body] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserAuthApi
     */
    public async userAuthRegisterPost(body?: UserRegisterReq, options?: AxiosRequestConfig) : Promise<AxiosResponse<LoginRes>> {
        return UserAuthApiFp(this.configuration).userAuthRegisterPost(body, options).then((request) => request(this.axios, this.basePath));
    }
}
